### ISSUE TITLE
When i login, app crashes.

### ISSUE THREAD

**Issue by Feelthewind** [yoonjaepark/flutter_naver_login#14]
await FlutterNaverLogin.logIn(); => App crashes.
Do you have any idea why this happens? Thanks.

E/AndroidRuntime(21523): FATAL EXCEPTION: main
E/AndroidRuntime(21523): Process: com.example.naver_login_test, PID: 21523
E/AndroidRuntime(21523): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/appcompat/R$style;
E/AndroidRuntime(21523): 	at com.nhn.android.naverlogin.ui.OAuthLoginDialogMng.showProgressDlg(OAuthLoginDialogMng.java:35)
E/AndroidRuntime(21523): 	at com.nhn.android.naverlogin.ui.OAuthLoginActivity$GetAccessTokenTask.onPreExecute(OAuthLoginActivity.java:412)
E/AndroidRuntime(21523): 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:648)
E/AndroidRuntime(21523): 	at android.os.AsyncTask.execute(AsyncTask.java:595)
E/AndroidRuntime(21523): 	at com.nhn.android.naverlogin.ui.OAuthLoginActivity.onActivityResult(OAuthLoginActivity.java:403)
E/AndroidRuntime(21523): 	at android.app.Activity.dispatchActivityResult(Activity.java:7762)
E/AndroidRuntime(21523): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4603)
E/AndroidRuntime(21523): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
E/AndroidRuntime(21523): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(21523): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(21523): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(21523): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
E/AndroidRuntime(21523): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21523): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(21523): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/AndroidRuntime(21523): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21523): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(21523): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/AndroidRuntime(21523): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.appcompat.R$style" on path: DexPathList[[zip file "/data/app/com.example.naver_login_test-Yzb6gRLoRnPUdUCgOeLMIA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.naver_login_test-Yzb6gRLoRnPUdUCgOeLMIA==/lib/arm64, /data/app/com.example.naver_login_test-Yzb6gRLoRnPUdUCgOeLMIA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
E/AndroidRuntime(21523): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(21523): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(21523): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(21523): 	... 18 more
I/Process (21523): Sending signal. PID: 21523 SIG: 9

**Comment by yoonjaepark** [comment]
Have you done the NAVER API settings?
