### ISSUE TITLE
it's ... I have nothing to do with it

### ISSUE THREAD

**Issue by bakboem** [yoonjaepark/flutter_naver_login#16]
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 8 is available at: http://127.0.0.1:52686/r83lW7jo2Tg=/
URL scheme for KakaoOpenSDK is not set properly in plist.
URL scheme for KakaoOpenSDK is not set properly in plist.

**Comment by yjpark0108** [comment]
Kakao???.. I don't know what you're talking about.

**Comment by yoonjaepark** [comment]
Kakao???.. I don't know what you're talking about. Can you speak Korean if you are Korean? 한국 사람 아니신가요?

**Comment by bakboem** [comment]
sorry~ 
I am Chinese, English and Korean are not very good. 
yes, that was Kakao's problem.
When flutter_kakao_login and  flutter_naver_login are working on the same project, this problem will appear.

**Comment by yoonjaepark** [comment]
> sorry~
> I am Chinese, English and Korean are not very good.
> yes, that was Kakao's problem.
> When flutter_kakao_login and flutter_naver_login are working on the same project, this problem will appear.

Okey, but I'm not sure about the Kakao_login issue. I have to take a test, too. And people seem to have been recommending kakao_flutter_sdk more than flutter_kakao_login.
