### ISSUE TITLE
flutter_naver_login을 사용하면 다른 플러그인을 사용하는 코드에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by rlaeoghks78** [yoonjaepark/flutter_naver_login#18]
안녕하세요~
AgoraIO(https://github.com/AgoraIO/Flutter-SDK) 플러그인 사용중입니다.
readme파일의 에러 핸들링부분에 나온 대로 MainActivity.kt 파일의 소스코드를 아래와 같이 수정했습니다.
```
class MainActivity: FlutterActivity() {  
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        //GeneratedPluginRegistrant.registerWith(flutterEngine)
        SurfaceView(applicationContext).setSecure(true);
        this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);
    }
}
```

앱을 실행하면 아래와 같이 로그가 출력됩니다.
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(11839): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(11839): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(11839): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
W/FlutterEngine(11839): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@38b6fa5) but could not find and invoke the GeneratedPluginRegistrant.
D/FlutterActivityAndFragmentDelegate(11839): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(11839): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@38b6fa5
D/FlutterActivityAndFragmentDelegate(11839): Executing Dart entrypoint: main, and sending initial route: /

워닝 로그 발생한 후 다른 플러그인을 사용하는 부분에서 아래와 같은 에러가 발생합니다.
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method keepOn on channel github.com/clovisnicolas/flutter_screen))

pubspec.yaml파일에서 flutter_naver_login부분을 삭제하면 아래와 같이 워닝로그가 사라지면서 실행에 문제가 없습니다.
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(12230): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(12230): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(12230): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(12230): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(12230): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@8cda485
D/FlutterActivityAndFragmentDelegate(12230): Executing Dart entrypoint: main, and sending initial route: /

MainActivity.kt에서 GeneratedPluginRegistrant.registerWith()함수를 호출하지 않아서 생기는 문제 같은데 
GeneratedPluginRegistrant.registerWith()함수를 사용하지 않으면서 flutter_naver_login플러그인을 사용할 수 있는 방법은 없을까요?
감사합니다!

[flutter] flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale ko-KR)
    • Flutter version 1.12.13+hotfix.9 at D:\Work\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\abcde\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\abcde\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5556      • android-x86   • Android 10 (API 29) (emulator)

**Comment by yoonjaepark** [comment]
flutter 버전이 올라가면서 flutterEngine을 사용하게 변경 된거같은데
플러그인 버전 마이그레이션 하고나서 한번 테스트 부탁드립니다.

**Comment by yoonjaepark** [comment]
> 안녕하세요~
> AgoraIO(https://github.com/AgoraIO/Flutter-SDK) 플러그인 사용중입니다.
> readme파일의 에러 핸들링부분에 나온 대로 MainActivity.kt 파일의 소스코드를 아래와 같이 수정했습니다.
> 
> ```
> class MainActivity: FlutterActivity() {  
>     override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>     }
> 
>     override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
>         super.configureFlutterEngine(flutterEngine)
>         //GeneratedPluginRegistrant.registerWith(flutterEngine)
>         SurfaceView(applicationContext).setSecure(true);
>         this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);
>     }
> }
> ```
> 
> 앱을 실행하면 아래와 같이 로그가 출력됩니다.
> √ Built build\app\outputs\apk\debug\app-debug.apk.
> D/FlutterActivity(11839): Using the launch theme as normal theme.
> D/FlutterActivityAndFragmentDelegate(11839): Setting up FlutterEngine.
> D/FlutterActivityAndFragmentDelegate(11839): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
> W/FlutterEngine(11839): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@38b6fa5) but could not find and invoke the GeneratedPluginRegistrant.
> D/FlutterActivityAndFragmentDelegate(11839): Attaching FlutterEngine to the Activity that owns this Fragment.
> D/FlutterView(11839): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@38b6fa5
> D/FlutterActivityAndFragmentDelegate(11839): Executing Dart entrypoint: main, and sending initial route: /
> 
> 워닝 로그 발생한 후 다른 플러그인을 사용하는 부분에서 아래와 같은 에러가 발생합니다.
> Exception has occurred.
> MissingPluginException (MissingPluginException(No implementation found for method keepOn on channel github.com/clovisnicolas/flutter_screen))
> 
> pubspec.yaml파일에서 flutter_naver_login부분을 삭제하면 아래와 같이 워닝로그가 사라지면서 실행에 문제가 없습니다.
> √ Built build\app\outputs\apk\debug\app-debug.apk.
> D/FlutterActivity(12230): Using the launch theme as normal theme.
> D/FlutterActivityAndFragmentDelegate(12230): Setting up FlutterEngine.
> D/FlutterActivityAndFragmentDelegate(12230): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
> D/FlutterActivityAndFragmentDelegate(12230): Attaching FlutterEngine to the Activity that owns this Fragment.
> D/FlutterView(12230): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@8cda485
> D/FlutterActivityAndFragmentDelegate(12230): Executing Dart entrypoint: main, and sending initial route: /
> 
> MainActivity.kt에서 GeneratedPluginRegistrant.registerWith()함수를 호출하지 않아서 생기는 문제 같은데
> GeneratedPluginRegistrant.registerWith()함수를 사용하지 않으면서 flutter_naver_login플러그인을 사용할 수 있는 방법은 없을까요?
> 감사합니다!
> 
> [flutter] flutter doctor -v
> [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale ko-KR)
> • Flutter version 1.12.13+hotfix.9 at D:\Work\flutter
> • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
> • Engine revision af51afceb8
> • Dart version 2.7.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at C:\Users\abcde\AppData\Local\Android\sdk
> • Android NDK location not configured (optional; useful for native profiling support)
> • Platform android-29, build-tools 29.0.3
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 44.0.2
> • Dart plugin version 192.7761
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.44.0)
> • VS Code at C:\Users\abcde\AppData\Local\Programs\Microsoft VS Code
> • Flutter extension version 3.9.1
> 
> [√] Connected device (3 available)
> • Android SDK built for x86 • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

버전업 했습니다 테스트 부탁드립니다

**Comment by rlaeoghks78** [comment]
버전업하고 문제 없이 잘 됩니다.
빠른 피드백 감사드립니다.
수고하세요~
