### ISSUE TITLE
로그인 후 페이지를 찾을 수 없습니다 문제

### ISSUE THREAD

**Issue by ehowlsla** [yoonjaepark/flutter_naver_login#19]
ios 기기에서 flutter sdk를 통해 

로그인 후 (현재 앱은 개발중 상태)

account 정보가 리턴되면서 로그인 창이 닫힐 것으로 예상을 했는데,

페이지를 찾을 수 없습니다. 라는 화면이 보여지네요

flutter ios에서 왜 굳이 페이지를 찾을 수 없습니다가 나오는건지는 모르겠습니다.

**Comment by yoonjaepark** [comment]
url 스킴이랑 AppDelegate에 추가 코드 넣는 부분 확인이 필요할꺼 같습니다!
