### ISSUE TITLE
Naver login redirecting issue

### ISSUE THREAD

**Issue by ShilpaVania** [yoonjaepark/flutter_naver_login#22]
Whenever i click on login with naver it's redirect to page in which i am getting error of this page can not be found take naver help 
can you please let us know what issue it could be?

![image](https://user-images.githubusercontent.com/72484634/95288137-423e8c00-0885-11eb-90bf-da579962d384.png)

**Comment by jpoh281** [comment]
I have the same problem.
How did you solve it?

**Comment by yoonjaepark** [comment]
@jpoh281 , @KuldeepVagadiya , @ShilpaVania  네이버 가이드 문서를 api key나 scheme, scheme, appName 등 관련 값이 다를 경우 위 같은 에러가 발생합니다.
더 정확한 내용은 네이버 문서를 보는게 정확할 겁니다.

**Comment by KuldeepVagadiya** [comment]
@yoonjaepark 네 맞습니다, 이제 naver 로그인 페이지로 리디렉션하고 있지만 이제 naver가 내 응답에 null 데이터를 반환합니다. 모든 계정 세부 정보가 null이고 accessToken도 null입니다.이 문제를 해결하도록 도와주세요.

**Comment by ShilpaVania** [comment]
@yoonjaepark 
i was also having the same issue about getting null data from plugin and it's also worked in emulator sometime so i think it should be issue of certification of domain for api calling which is used in naver login plugin and i couldn't figure it out.
