### ISSUE TITLE
Got Exception after login 

### ISSUE THREAD

**Issue by ShilpaVania** [yoonjaepark/flutter_naver_login#23]
javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7f66933c80: I/O error during system call, Connection reset by peer
W/System.err( 4913): org.json.JSONException: End of input at character 0 of 
W/System.err( 4913): 	at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
W/System.err( 4913): 	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
W/System.err( 4913): 	at org.json.JSONObject.<init>(JSONObject.java:156)
W/System.err( 4913): 	at org.json.JSONObject.<init>(JSONObject.java:173)

please help me with it and let me know issue is could

**Comment by yoonjaepark** [comment]
재현 방법 알려주시면 확인해보겠습니다.
