### ISSUE TITLE
로그인시 _TypeError(type 'Null' is not a subtype of type 'String') 발생

### ISSUE THREAD

**Issue by gkssk925** [yoonjaepark/flutter_naver_login#32]

**Comment by ska2519** [comment]
@gkssk925 
flutter 2.0에서 저도 로그인 시 access_token 받아 오는데도
_TypeError (type 'Null' is not a subtype of type 'String') 발생하는데 어떻게 해결하셨어요?

![Screen Shot 2021-04-30 at 3 11 13 PM](https://user-images.githubusercontent.com/15642712/116655582-4f100200-a9c6-11eb-9536-5e8216584f51.png)
