### ISSUE TITLE
ios 에서 missingPluginException 발생

### ISSUE THREAD

**Issue by Acver14** [yoonjaepark/flutter_naver_login#38]
readMe에 나온대로 적용시 shared_preferences, firebase_auth 등 모든 라이브러리에서 MissingPluginException을 발생시킵니다.

AppDelegate.swift
`import UIKit
import Flutter
import Firebase
import GoogleMaps
import NaverThirdPartyLogin

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    open url: URL,
    options: [UIApplication.OpenURLOptionsKey : Any] = [:])  -> Bool {
    GMSServices.provideAPIKey("구글맵키")
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    
    return NaverThirdPartyLoginConnection.getSharedInstance().application(application, open: url, options: options)
  }
}
`

이전 AppDelegate.swift 코드는아래와 같습니다
`import UIKit
import Flutter
import Firebase
import GoogleMaps

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GMSServices.provideAPIKey("구글맵키")
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}`

**Comment by Acver14** [comment]
swift 파일에서 application 분기하여 해결

**Comment by arkang18** [comment]
> swift 파일에서 application 분기하여 해결

같은 현상 발생중인데 
혹시 어떻게 해결하셨는지
AppDelegate.swift 파일 
예시로 올려주실수있을까요..??

**Comment by Acver14** [comment]
처음에 제가 적용하는 방법을 몰라서 해멨던 건지 저는 기존 application 클래스 분기해서 새 application 생성하여 해결했었는데
해결하셨나요?
