### ISSUE TITLE
가입여부와 상관없이 개인정보 접근 동의 팝업이 로그인 할때마다 계속 뜨고 있습니다.

### ISSUE THREAD

**Issue by shinji-studypie** [yoonjaepark/flutter_naver_login#39]
가입여부와 상관없이 이미 가입한 유저와

가입하지 않은유저 가리지 않고 개인정보 접근 동의 팝업이 로그인 할때마다 계속 뜨고 있습니다.

**Comment by yoonjaepark** [comment]
로그아웃시 토큰을 삭제해서 그런것같습니다. 토큰 삭제하지 않은 로그아웃 메소드를 배포할 에정입니다.
