### ISSUE TITLE
Flutter 2.5.0 업데이트 이후 오류 

### ISSUE THREAD

**Issue by CHOI-YOOBIN** [yoonjaepark/flutter_naver_login#41]
Flutter 2.5.0 업데이트 ios 오류가 발생했습니다.
특이하게 xcode에서 빌드를 하면 문제없지만, android studio에서 simulator를 빌드를 하면 오류가 발생합니다.
네이버 로그인 플러그인으로 인해 오류가 발생한것으로 보입니다.

` /Users/billyo.dev/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_naver_login-1.2.2/ios/Classes/FlutterNaverLoginPlugin.m:24:39: warning: assigning to 'id<NaverThirdPartyLoginConnectionDelegate>' from incompatible type 'FlutterNaverLoginPlugin *__strong'
            _thirdPartyLoginConn.delegate = self;
                                          ^ ~~~~
    /Users/billyo.dev/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_naver_login-1.2.2/ios/Classes/FlutterNaverLoginPlugin.m:78:45: warning: 'sendSynchronousRequest:returningResponse:error:' is deprecated: first deprecated in iOS 9.0 - Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h [-Wdeprecated-declarations]
        NSData *receivedData = [NSURLConnection sendSynchronousRequest:urlRequest returningResponse:&response error:&error];
                                                ^
    In module 'UIKit' imported from /Users/billyo.dev/billyo/project/billyo/ios/Pods/Target Support Files/flutter_naver_login/flutter_naver_login-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLConnection.h:405:1: note: 'sendSynchronousRequest:returningResponse:error:' has been explicitly marked deprecated here
    + (nullable NSData *)sendSynchronousRequest:(NSURLRequest *)request returningResponse:(NSURLResponse * _Nullable * _Nullable)response error:(NSError **)error API_DEPRECATED("Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h", macos(10.3,10.11), ios(2.0,9.0), tvos(9.0,9.0)) API_UNAVAILABLE(watchos);
    ^
    /Users/billyo.dev/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_naver_login-1.2.2/ios/Classes/FlutterNaverLoginPlugin.m:86:87: warning: incompatible pointer to integer conversion sending 'void *' to parameter of type 'NSJSONReadingOptions' (aka 'enum NSJSONReadingOptions') [-Wint-conversion]
            NSDictionary *dict = [NSJSONSerialization JSONObjectWithData:jsonData options:nil error:&e];
                                                                                          ^~~
    In module 'UIKit' imported from /Users/billyo.dev/billyo/project/billyo/ios/Pods/Target Support Files/flutter_naver_login/flutter_naver_login-prefix.pch:2:`

**Comment by tagby-igorhwang** [comment]
저도 비슷한 이슈를 겪어서 해결하는데 4일 이상 걸렸습니다.

Podspec 파일에 아래처럼 수정하시면 됩니다:

```
...
post_install do |installer|
   installer.pods_project.targets.each do |target|
   flutter_additional_ios_build_settings(target)
     target.build_configurations.each do |config|
       config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
       config.build_settings['ARCHS[sdk=iphonesimulator*]'] =  `uname -m`
     end
   end
 end
```

추가적으로 관련 [쓰레드](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io) 읽으셔서 해보시면 될듯 합니다.
