### ISSUE TITLE
refactor: ios prefix k to naver

### ISSUE THREAD

**Issue by jjangga0214** [yoonjaepark/flutter_naver_login#48]
```xml
        <key>kServiceAppUrlScheme</key>
        <string>[UrlScheme]</string>
        <key>kConsumerKey</key>
        <string>[ConsumerKey]</string>
        <key>kConsumerSecret</key>
        <string>[ConsumerSecret]</string>
        <key>kServiceAppName</key>
        <string>[ServiceAppName]</string>
```

Info.plist 에서 key 설정에 k 를 prefix 로 붙이고 있습니다. 

하지만 kConsumerKey 같은 표현은 너무 generic 해서 다른 설정과 중복될 수도 있고, 직관적으로 naver 관련 key 인지의 여부를 가리기 어럽습니다.

차라리, 예를 들면, prefix 를 k 대신 naver 로 하여 naverConsumerKey 와 같이 한다면 좋을 것입니다.

[공식 문서](https://developers.naver.com/docs/login/ios/ios.md) 에서 상수이름에 k 를 붙이는 동일 예시를 보여주기는 하지만, 그건 예시일 뿐입니다. 변수 이름은 우리가 마음대로 바꿀 수 있으니 리팩터링을 제안드립니다.

https://github.com/yoonjaepark/flutter_naver_login/blob/b983ba3e8c88d866fe1d7eb9797f3d7b79ea2e0c/ios/Classes/FlutterNaverLoginPlugin.m#L13-L22

**Comment by tagby-igorhwang** [comment]
지난 버전과 호환 안 되는 수정 하실 때 major 버전 넘버를 올리는 것이 좋을 것 같습니다.
