### ISSUE TITLE
login user cancel 시 error 가 리턴되지 않고 null 값이 return 됩니다

### ISSUE THREAD

**Issue by Jongwoo-Lee** [yoonjaepark/flutter_naver_login#6]
안드로이드에서 login user cancel 시 error 가 리턴되지 않고 null 값이 return 됩니다
kotlin 파일에서 133번째줄 result.success(null) 을 지우니 error 리턴 받고 잘 돌아갔습니다.

**Comment by yoonjaepark** [comment]
피드백 감사드립니다!!

반영해서 업데이트 적용했습니다!

2019. 6. 25. 15:54, 이종우 <notifications@github.com> 작성:
