### ISSUE TITLE
NaverAccountResult에 birthyear값이 없는 현상

### ISSUE THREAD

**Issue by mero-jung** [yoonjaepark/flutter_naver_login#61]
네이버 문서 상에는 birthyear(태어난 년도)에 대한 표시가 되어있고, 해당 class에서 birthyear를 추가해서 값이 받아지는 것을 확인했습니다. 그래서 정식 pub에 해당 부분이 적용 가능할까요?

**Comment by yoonjaepark** [comment]
넵 주말에 확인해보고 업데이트 하겠습니다.

**Comment by yoonjaepark** [comment]
https://github.com/yoonjaepark/flutter_naver_login#how-do-i-use-it

속성 추가해서 배포했습니다. :)
