### ISSUE TITLE
android 12 릴리즈 일시 Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by Kimhyunsu92** [yoonjaepark/flutter_naver_login#66]
E/flutter (15392): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method logIn on channel flutter_naver_login)
E/flutter (15392): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175)
E/flutter (15392): <asynchronous suspension>
E/flutter (15392): #1      FlutterNaverLogin.logIn (package:flutter_naver_login/flutter_naver_login.dart:11)
E/flutter (15392): <asynchronous suspension>
E/flutter (15392): #2      AuthController._getAccountInfo (package:dalgo3/controllers/auth_controller.dart:96)
E/flutter (15392): <asynchronous suspension>
E/flutter (15392): 

디버그에선 정상적으로 로그인이 되지만 flutter run --release 시 해당 에러가 발생합니다.
이부분에 대해 제가 고쳐야할게 있을까요?

**Comment by LeGoffMael** [comment]
Did you managed to fix your issue @Kimhyunsu92 ?
It is working fine with an APK but i am facing the same issue when i submit the app to the PlayStore

```
MissingPluginException: MissingPluginException(No implementation found for method logIn on channel flutter_naver_login)
  File "platform_channel.dart", line 165, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "flutter_naver_login.dart", line 11, in FlutterNaverLogin.logIn
  File "<asynchronous suspension>"
```

**Comment by mero-jung** [comment]
저도 동일한 문제가 있는데 queries에 naver앱 package를 추가해야하는건지 모르겠네요...

**Comment by mero-jung** [comment]
AndroidManifest.xml에 <manifest> 내부에서 다음 코드를 추가하니까 해결되던데 한번 확인해보시면 될 것 같아요

``` xml
<queries>
    <package android:name="com.nhn.android.search" />
</queries>
```
@Kimhyunsu92

**Comment by ctrlcv** [comment]
혹시 이 이슈 해결하셨나요? 저도 동일한 이슈가 발생하는데 @mero-jung 님이 알려주신 방법으로도 해결이 안 되네요...

**Comment by postklee15** [comment]
저도 동일한 이슈로 디버그로 단말에 올렸을 때는 문제가 없는데, 플레이 스토어 업데이트 후에 MissingPluginException 에러가 발생하고 있네요. @mero-jung 님이 제안해주신 방법으로 해결은 안되고 있네요.

빌드 환경을 SDK 30으로 낮춰볼까도 했는데 다른 패키지들이 31에 의존적인 걸 너무 많이 쓰고 있어서 SDK 30으로 낮추지는 못하고 있습니다.

빌드 환경은 다음과 같습니다.
Android SDK 31
Flutter 3.0.5
flutter_naver_login 1.6.0
