### ISSUE TITLE
Android 로그인시 PlatformException(error, lateinit property launcher has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property launcher has not been initialized

### ISSUE THREAD

**Issue by sinadsl1457** [yoonjaepark/flutter_naver_login#78]
iOS는 정상적으로 로그인이 되는데요 갑자기 안드로이드만 이런 에러가 나옵니다 무슨 문제일까요?

**Comment by ShinJinBum** [comment]
저도 갑자기 안돼서 문의하러 왔다가 해결하고 갑니다~

라이브러리 안드로이드쪽 설명에 아래 문구가 추가됐더라구요

It is also necessary to uses FlutterFragmentActivity instead of FlutterActivity since uses of naver sdk 5.2.0.

import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity()

**Comment by sinadsl1457** [comment]
> 

정말 감사합니다 ㅠㅠ
