### ISSUE TITLE
Hello, i can run app on iphone with naver plugin , but when i try to login and go to naver app and back to my app , i dont get any result , so plz help me

### ISSUE THREAD

**Issue by rocky-concetto** [yoonjaepark/flutter_naver_login#8]

**Comment by yoonjaepark** [comment]
Did you sign in to Naver App? 
I am aware of the issue.  I try to solve it as time goes by.
However, currently Naver app can not log in. 
When you update to the latest version, you have the app sign-in and changed the sign in with the app browser.
I have disabled iOS Naver login at latest version.

**Comment by rocky-concetto** [comment]
i have login in naver app , and back to my app , do you mean need to unintall naver app and try to login in naver with brower , right?

**Comment by yoonjaepark** [comment]
> i have login in naver app , and back to my app , do you mean need to unintall naver app and try to login in naver with brower , right?

If you install the latest plug-in, login through the Naver app was disabled.
iOS WebView login changed to connect.

**Comment by yoonjaepark** [comment]
![153758286](https://user-images.githubusercontent.com/6939460/62189715-af65b000-b3aa-11e9-87f7-8420926d744b.jpg)

**Comment by rocky-concetto** [comment]
Yes , i have try to login with latest plugin, plz let me check with brower login

**Comment by yoonjaepark** [comment]
> Yes , i have try to login with latest plugin, plz let me check with brower login

Thank you. feed back.
I will update it with iOS and Naver app later.

**Comment by rocky-concetto** [comment]
Hello, i have check with browser login and its work , can i which plugin version support naver app login ? , if no plz add support for naver app

**Comment by yoonjaepark** [comment]
Support last version 

dependencies:
  flutter_naver_login: ^0.3.2

**Comment by rocky-concetto** [comment]
can i check this version with app login?

**Comment by yoonjaepark** [comment]
Sure.  This issue already closed. 
https://github.com/yoonjaepark/flutter_naver_login/issues/7

**Comment by rocky-concetto** [comment]
Please add app Naver app login support then close the issue , this works with browser but not works with app

**Comment by yoonjaepark** [comment]
Ok. I have already added it to readme document.

**Comment by rocky-concetto** [comment]
Okay, Please enable app login as soon as possible , thank you

**Comment by yoonjaepark** [comment]
> Ok. I have already added it to readme document.


You can log in using the iOS naver app by viewing the 0.3.4 version and the Readme document.

**Comment by rocky-concetto** [comment]
thank you , i can login with ios naver app now with 0.3.4 version
