### ISSUE TITLE
iOS에서 네이버 앱을 통한 로그인 시 진행이 되지 않습니다.

### ISSUE THREAD

**Issue by uhm0311** [yoonjaepark/flutter_naver_login#9]
안녕하세요. 네이버 로그인 플러그인 잘 쓰고 있습니다. iOS로 테스트를 하는데 네이버 앱이 설치된 디바이스에서는 로그인 진행이 되질 않고 네이버 앱이 설치되지 않은 디바이스에서는 정상적으로 진행됩니다. 네이버 앱을 통해 로그인을 시도해도 별 다른 로그는 없었습니다. 

자료를 조사 해보니 아래의 게시글의 댓글에서 이슈와 관련되어 보이는 부분을 발견했습니다.

https://baked-corn.tistory.com/m/119

댓글에서 네이버 앱을 통한 로그인을 진행하려면 추가 처리가 필요하다고 합니다. 해당 부분 플러그인에 반영 가능하신지요?

**Comment by yoonjaepark** [comment]
네 안녕하세요
네이버 앱관련된 이슈는 해결해서 #8 클로즈 해놨습니다.
혹시 안되신다면 플러그인 버전이 몇인지 알 수 있을까요?
현재 0.3.4 버전은 해당 이슈 해결됐다고 피드백 받았습니다.

**Comment by uhm0311** [comment]
사용 버전은 0.3.4입니다. 아무런 로그도 뜨지 않아서 더 자세한 정보를 드릴 수가 없네요.

**Comment by yoonjaepark** [comment]
제가 Readme에보시면

 <your project root>ios/Runner/ios/Runner/AppDelegate.m

아래 코드 추가해주셨나요?? 

// Implemented when iOS 9.0 Less
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    return [[NaverThirdPartyLoginConnection getSharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
}

// Implemented when iOS 9.0 higher

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
    return [[NaverThirdPartyLoginConnection getSharedInstance] application:app openURL:url options:options];
}

**Comment by uhm0311** [comment]
아! 해당 부분이 필요했군요. 죄송합니다.
혹시 Readme에 해당 부분을 AppDelegate.m에 추가해야 한다고 명시해주실 수 있나요? 현재는 어디에 넣어야 하는지 까진 명시되어 있지 않아서요. 그리고 제가 잘 몰라서 그러는데 NaverThirdPartyLoginConnection 클래스를 사용하기 위해서 어떤 헤더를 임포트/인클루트 해야 하는지도 알려주시면 감사하겠습니다.

**Comment by yoonjaepark** [comment]
이미 리드미에 언급은 되있습니다ㅜㅜㅜ
저내용은 리드미에서 복사해서 드린겁니다 ㅜㅜㅜ

**Comment by yoonjaepark** [comment]
클래스는 제가 집에서 확인은 해볼텐데 무슨 클래스인지 알수있을까요??? Ios 네이티브 부분 말하시는건가요?

**Comment by uhm0311** [comment]
앗 flutter pub에서의 Readme만 봐서 몰랐는데 github의 Readme도 확인해보니 있네요. 번거롭게 해서 죄송합니다.
클래스 부분은 해당 코드의 NaverThirdPartyLoginConnection를 사용하기 위해서 어떤 헤더를 가져와야 하는지인데 검색을 해보니 #import <NaverThirdPartyLogin/NaverThirdPartyLogin.h> 문구를 추가하면 되는 걸로 나왔어요. 이 문구도 코드에 함께 있으면 좋을 것 같습니다.

**Comment by yoonjaepark** [comment]
넵 조만간 릴리즈 시킬때 포함시키겠습니다

**Comment by yoonjaepark** [comment]
확인해본결과 pub 0.34버전 문서에도 현재 버전과 동일한 Readme 내용이 있고 
ios 클래스 헤더는 에초에 패키지 받으면 선언되있는 부분이라 사용자가 딱히 설정할 필요는 없다고 파악되서 이슈 닫도록 하겠습니다.
