### ISSUE TITLE
cloud ci 에서 빌드하면 'NaverThirdPartyLogin/NaverThirdPartyLogin.h' file not found 에러가 납니다

### ISSUE THREAD

**Issue by edupanions** [yoonjaepark/flutter_naver_login#97]
로컬에서 빌드할때는 문제가 없는데요
circleci에서 빌드하면 'NaverThirdPartyLogin/NaverThirdPartyLogin.h' file not found 이런 에러가 발생하는데
뭐가 문제일까요?

**Comment by Heewookji** [comment]
저도 github action에서만 동일한 오류가 났는데
CI 쪽에서 Xcode 버전을 latest stable로 올려서 해결됐습니다.
arm arch 관련한 에러인 듯 합니다..

[참고 링크](https://stackoverflow.com/questions/71724105/how-do-i-resolve-lexical-or-preprocessor-issue-xcode-flutter-flutter-h-fil)

**Comment by hanbit-edu** [comment]
@Heewookji 답변 감사드립니다~!

**Comment by edupanions** [comment]
@Heewookji 답변 감사드립니다~!!
